version: '3'
services:
  redis:
    image: redis
    container_name: redis
  db:
    image: postgres:9.4
    container_name: db
  voting-app:
    image: dockersamples/examplevotingapp_vote
    ports:
      - '5000:80'
    depends_on:
      - db
  worker-app:
    image: dockersamples/examplevotingapp_worker
    depends_on:
      - redis
      - db
  resuting-app:
    image: dockersamples/examplevotingapp_result
    ports:
      - '5001:80'
    depends_on:
      - db